---

- import_tasks: repo.yml
- import_tasks: install.yml
- import_tasks: system_tweaks.yml
  when:
    - mongodb_system_tweaks_enabled
- import_tasks: config.yml
- import_tasks: service.yml
- import_tasks: sensu_checks.yml
  when:
    - (mongodb_sensu_checks_enabled or mongodb_remove_sensu_checks)

- name: wait for mongodb to start
  wait_for:
    host: "{{ mongodb_config_net.bindIp }}"
    port: "{{ mongodb_config_net.port }}"
    delay: 2
    connect_timeout: 1
    timeout: 30
  when:
    - mongodb_wait_for_start | default(true)
  tags:
    - mongodb_status

- import_tasks: mongo_shell.yml
  when:
    - mongodb_shell_execute_enabled
    - mongodb_shell_commands is defined
  tags:
    - mongo_shell
