---

- name: installing sensu plugin pkg requirements
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - "{{ mongodb_sensu_plugin_pkgs_required }}"
  when:
    - mongodb_sensu_checks_enabled
    - not mongodb_remove_sensu_checks

- name: installing required sensu check bins
  copy:
    src: "{{ item.filename }}"
    dest: "{{ item.dest | default('/opt/sensu/embedded') }}/{{ item.filename }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ mongodb_sensu_bins }}"
  when:
    - mongodb_sensu_checks_enabled
    - not mongodb_remove_sensu_checks

- name: installing mongodb sensu plugins
  environment: "{{ proxy_env | default(omit) }}"
  gem:
    name: "{{ item.plugin_name }}"
    version: "{{ item.plugin_version | default(omit) }}"
    state: present
    executable: "{{ mongodb_sensu_plugin_executable }}"
    user_install: false
  with_items:
    - "{{ mongodb_sensu_plugins }}"
  notify:
    - restart sensu-client
  when:
    - mongodb_sensu_checks_enabled
    - not mongodb_remove_sensu_checks

- name: creating mongodb sensu check definitions
  sensu_check:
    name: "{{ item.key }}"
    command: "{{ item.value.command }}"
    interval: "{{ item.value.interval }}"
    path: "{{ mongodb_sensu_checks_dir }}/{{ item.key | regex_replace(' ', '_') }}.json"
    ttl: "{{ item.value.ttl | default(omit) }}"
    standalone: true
  with_dict: "{{ mongodb_sensu_checks }}"
  notify:
    - restart sensu-client
  when:
    - mongodb_sensu_checks_enabled
    - not mongodb_remove_sensu_checks

# removal of checks

- name: remove mongodb sensu check definitions
  file:
    path: "{{ mongodb_sensu_checks_dir }}/{{ item.key | regex_replace(' ', '_') }}.json"
    state: absent
  with_dict: "{{ mongodb_sensu_checks }}"
  notify:
    - restart sensu-client
  when:
    - mongodb_remove_sensu_checks

- name: remove required sensu check bins
  file:
    path: "{{ item.dest | default('/opt/sensu/embedded') }}/{{ item.filename }}"
    state: absent
  with_items:
    - "{{ mongodb_sensu_bins }}"
  when:
    - mongodb_remove_sensu_checks
