---

- name: "restart {{ mongodb_service_name }} service"
  systemd:
    name: "{{ mongodb_service_name }}"
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart sensu-client
  systemd:
    name: "{{ mongodb_sensu_service_name }}"
    state: restarted
